Traceback (most recent call last):
  File "/home/mb2023/my_hpc_projects/synthcity-docker-project/generating.py", line 17, in <module>
    synmed = SynthMed(
             ^^^^^^^^^
TypeError: SynthMed.__init__() got an unexpected keyword argument 'target_column'
